### ISSUE TITLE
Doesn't work on windows because copy is a built in command

### ISSUE THREAD

**Issue by pflannery** [ihaichao/copy-dir-cli#1]
Hi this works great but on windows running `copy src/somedir out` from inside npm run-scripts shows an error `The syntax of the command is incorrect.`

The error happens because npm executes the built in `copy` command on windows

Is possible to include an extra bin alias like

```json
"bin": {
  "copy": "./bin/copy",
  "copydir": "./bin/copy"
}
```

**Comment by ihaichao** [comment]
Hi, it's a CLI tool as the readme says. 
I think it's confused to add an extra bin with the same function, do you think so?
I recommed you to build a local file for npm scripts.

**Comment by pflannery** [comment]
I don't really want to have local files in the project. 
Its ok I understand if you don't include an additional bin alias.
thanks
